//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTUAL_SAVINGS
    {
        public int ACTUAL_SAVINGS_ID { get; set; }
        public string FINANCIAL_YEAR { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> SAVINGS_DATE { get; set; }
        public string CERTIFICATE_NO { get; set; }
        public Nullable<int> NO_MONTHS { get; set; }
        public Nullable<System.DateTime> AUTH_DATE { get; set; }
        public string AUTH_BY { get; set; }
        public Nullable<System.DateTime> AUTH_TIME { get; set; }
        public string AUTH_COMPUTER { get; set; }
        public Nullable<int> AGREEMENT_CODE { get; set; }
    
        public virtual EMP_FIXED EMP_FIXED { get; set; }
        public virtual TAX_CODE TAX_CODE { get; set; }
        public virtual AGREEMENT_DETAILS AGREEMENT_DETAILS { get; set; }
    }
}
