//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESSEE_MASTER
    {
        public int ADDRESSID { get; set; }
        public string ADDR0 { get; set; }
        public string ADDR1 { get; set; }
        public string CITY { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual COMPANY_PARAMETER COMPANY_PARAMETER { get; set; }
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
    }
}
