//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEDCODE
    {
        public int Id { get; set; }
        public short CODE { get; set; }
        public string DESCR { get; set; }
        public string AED { get; set; }
        public string EARNING_TYPE { get; set; }
        public string EMP_BRK { get; set; }
        public string TAXABLE_YN { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public string ACCODE { get; set; }
        public string SUBCD { get; set; }
        public string ACDESC { get; set; }
        public string EDDESC { get; set; }
        public string DC { get; set; }
        public string INT_YN { get; set; }
        public Nullable<decimal> INT_RATE { get; set; }
        public string PTAX_YN { get; set; }
        public string ESI_YN { get; set; }
        public string DETAIL_YN { get; set; }
    }
}
