//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOTMENT
    {
        public int Id { get; set; }
        public Nullable<byte> EMPL_CLASS { get; set; }
        public Nullable<int> EMPL_Id { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> ALLOT_AMOUNT { get; set; }
        public string PAYMENT_AT { get; set; }
        public string PAYMENT_REASON { get; set; }
        public string CURRENCY { get; set; }
        public string PMNT_MODE { get; set; }
        public string ALLOTTEE_NAME { get; set; }
        public string BANK_AC_NO { get; set; }
        public string BANK_NAME { get; set; }
        public Nullable<int> ALLOT_SL_NO { get; set; }
        public Nullable<int> SHIP_Id { get; set; }
        public string CHEQUE_NO { get; set; }
        public string PMNT_VOUCHER_NO { get; set; }
        public Nullable<System.DateTime> VOUCHER_DATE { get; set; }
        public Nullable<System.DateTime> CHEQUE_DATE { get; set; }
        public int REC_NO { get; set; }
        public string VCH_ADD_BY { get; set; }
        public Nullable<System.DateTime> VCH_ADD_TIME { get; set; }
        public string VCH_EDIT_BY { get; set; }
        public Nullable<System.DateTime> VCH_EDIT_TIME { get; set; }
        public string VCH_ADD_COMPUTER { get; set; }
        public string VCH_EDIT_COMPUTER { get; set; }
        public string PMNT_ADD_BY { get; set; }
        public Nullable<System.DateTime> PMNT_ADD_TIME { get; set; }
        public string PMNT_ADD_COMPUTER { get; set; }
        public string PMNT_EDIT_BY { get; set; }
        public Nullable<System.DateTime> PMNT_EDIT_TIME { get; set; }
        public string PMNT_EDIT_COMPUTER { get; set; }
        public string REMARKS { get; set; }
        public string MON { get; set; }
        public string YR { get; set; }
        public string CURR_CODE { get; set; }
        public Nullable<decimal> EXCH_RATE { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> REF_RECNO { get; set; }
        public string class_code { get; set; }
        public Nullable<int> RANK_CLASS_id { get; set; }
        public Nullable<bool> VOUCHER_PRINTED { get; set; }
    }
}
