//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_MASTER
    {
        public BANK_MASTER()
        {
            this.BRANCH_DETAILS = new HashSet<BRANCH_DETAILS>();
        }
    
        public int BANKID { get; set; }
        public string BANK_NAME { get; set; }
        public Nullable<bool> ACTIVE_BANK { get; set; }
        public string BANK_CODE { get; set; }
        public string ADD_BY { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public Nullable<System.DateTime> EDIT_TIME { get; set; }
    
        public virtual ICollection<BRANCH_DETAILS> BRANCH_DETAILS { get; set; }
    }
}
