//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH_DETAILS
    {
        public BRANCH_DETAILS()
        {
            this.COMPANY_BRANCH = new HashSet<COMPANY_BRANCH>();
            this.EMP_BRANCH = new HashSet<EMP_BRANCH>();
        }
    
        public int BRANCHID { get; set; }
        public string IFSCCODE { get; set; }
        public string SWIFTCODE { get; set; }
        public string MICRCODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string PIN { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public Nullable<int> BANKID { get; set; }
    
        public virtual BANK_MASTER BANK_MASTER { get; set; }
        public virtual ICollection<COMPANY_BRANCH> COMPANY_BRANCH { get; set; }
        public virtual ICollection<EMP_BRANCH> EMP_BRANCH { get; set; }
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
    }
}
