//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.DUTY_TYPE_MASTER = new HashSet<DUTY_TYPE_MASTER>();
            this.RANK_MASTER = new HashSet<RANK_MASTER>();
        }
    
        public int CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string CATEGORY_CODE { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<DUTY_TYPE_MASTER> DUTY_TYPE_MASTER { get; set; }
        public virtual ICollection<RANK_MASTER> RANK_MASTER { get; set; }
    }
}
