//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATE_MASTER
    {
        public int CERTID { get; set; }
        public string CERT_DESC { get; set; }
        public string PATH { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY { get; set; }
        public Nullable<System.DateTime> VALIDITY { get; set; }
        public Nullable<int> ISSUE_PLACE { get; set; }
        public Nullable<int> CTID { get; set; }
    
        public virtual CERTIFICATE_TYPE_MASTER CERTIFICATE_TYPE_MASTER { get; set; }
        public virtual EMP_FIXED EMP_FIXED { get; set; }
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
    }
}
