//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATE_TYPE_MASTER
    {
        public CERTIFICATE_TYPE_MASTER()
        {
            this.CERTIFICATE_MASTER = new HashSet<CERTIFICATE_MASTER>();
        }
    
        public int CTID { get; set; }
        public string CT_DESC { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<CERTIFICATE_MASTER> CERTIFICATE_MASTER { get; set; }
    }
}
