//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_MASTER
    {
        public CLIENT_MASTER()
        {
            this.CLIENT_USER = new HashSet<CLIENT_USER>();
            this.ShipAgreements = new HashSet<ShipAgreement>();
        }
    
        public int CLIENTID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string DATABASE_NAME { get; set; }
        public string DATABASE_HOST { get; set; }
        public string DATABASE_UID { get; set; }
        public string DATABASE_PASS { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string PIN { get; set; }
        public string PHONE { get; set; }
        public string FAX_NO { get; set; }
        public string EMAIL { get; set; }
        public string SERVICE_TAX_NO { get; set; }
        public string PICTURE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string DESCRIPTION { get; set; }
        public string CLIENT_LOGO { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public string CIN_NO { get; set; }
        public string PAN { get; set; }
        public string TAN { get; set; }
        public string WEBSITE { get; set; }
    
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
        public virtual ICollection<CLIENT_USER> CLIENT_USER { get; set; }
        public virtual ICollection<ShipAgreement> ShipAgreements { get; set; }
    }
}
