//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_COMMENT
    {
        public int COMMENTID { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> RECEIVERUSERID { get; set; }
        public Nullable<int> SENDERUSERID { get; set; }
        public Nullable<int> EMPID { get; set; }
        public Nullable<System.DateTime> COMMENTDATE { get; set; }
        public Nullable<bool> PRIVATE { get; set; }
        public Nullable<bool> PUBLIC { get; set; }
    
        public virtual EMP_FIXED EMP_FIXED { get; set; }
        public virtual EMP_FIXED EMP_FIXED1 { get; set; }
        public virtual EMP_FIXED EMP_FIXED2 { get; set; }
    }
}
