//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DG_CERTIFIED_DOCTORS
    {
        public int DGCDID { get; set; }
        public string DOCTOR_NAME { get; set; }
        public string CLINIC { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string PIN { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
    }
}
