//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTS_MASTER
    {
        public int DMID { get; set; }
        public string DMCODE { get; set; }
        public string DMDESCRIPTION { get; set; }
        public string PATH { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY { get; set; }
        public Nullable<System.DateTime> VALIDITY { get; set; }
        public Nullable<int> DT_ID { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public Nullable<int> ISSUE_PLACE { get; set; }
        public Nullable<int> MED_TYPE { get; set; }
    
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
        public virtual DOCUMENTS_TYPE DOCUMENTS_TYPE { get; set; }
        public virtual EMP_FIXED EMP_FIXED { get; set; }
    }
}
