//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTS_TYPE
    {
        public DOCUMENTS_TYPE()
        {
            this.DOCUMENTS_MASTER = new HashSet<DOCUMENTS_MASTER>();
        }
    
        public int DTID { get; set; }
        public string DTNAME { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<DOCUMENTS_MASTER> DOCUMENTS_MASTER { get; set; }
    }
}
