//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUTY_TYPE_MASTER
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public string ACTIVE { get; set; }
        public string EMP_TYPE { get; set; }
    
        public virtual CATEGORY CATEGORY1 { get; set; }
    }
}
