//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EARNING_DEDUCTION_MASTER
    {
        public short EARNDEDNID { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
