//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_EXPERIENCE
    {
        public int EEID { get; set; }
        public int EMP_id { get; set; }
        public string Company_Served { get; set; }
        public string Ship_name { get; set; }
        public Nullable<int> Ship_Type { get; set; }
        public string DWT { get; set; }
        public string Engine { get; set; }
        public string BHP { get; set; }
        public string Rank { get; set; }
        public Nullable<System.DateTime> Service_From { get; set; }
        public Nullable<System.DateTime> Service_To { get; set; }
        public Nullable<short> Months { get; set; }
        public Nullable<short> Days { get; set; }
        public Nullable<bool> DIRECT { get; set; }
        public string Area_Sp_Job { get; set; }
        public string Area_Operation { get; set; }
    
        public virtual SHIP_TYPE_MASTER SHIP_TYPE_MASTER { get; set; }
        public virtual EMP_FIXED EMP_FIXED { get; set; }
    }
}
