//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_SIGN
    {
        public EMP_SIGN()
        {
            this.FIXED_SALARY_DETAILS = new HashSet<FIXED_SALARY_DETAILS>();
        }
    
        public int Id { get; set; }
        public string EMP_CODE { get; set; }
        public int EMP_Id { get; set; }
        public string RANK_CODE { get; set; }
        public string NATURE_OF_DUTY { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string SHIP_CODE { get; set; }
        public Nullable<int> SHIP_Id { get; set; }
        public string ADD_BY { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string ADD_COMPUTER { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_TIME { get; set; }
        public string EDIT_COMPUTER { get; set; }
        public Nullable<decimal> WAGE { get; set; }
        public Nullable<int> PORT_Id { get; set; }
        public string CLASS_CODE { get; set; }
        public Nullable<int> AGREEMENT_Id { get; set; }
        public Nullable<decimal> BASIC_WAGES { get; set; }
        public Nullable<decimal> LEAVE_WAGES { get; set; }
        public Nullable<decimal> PF_AMT { get; set; }
        public Nullable<bool> PF_APPLICABLE { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual EMP_FIXED EMP_FIXED { get; set; }
        public virtual ICollection<FIXED_SALARY_DETAILS> FIXED_SALARY_DETAILS { get; set; }
    }
}
