//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_STATUS
    {
        public long EMPSTATID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_PERSONEL { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string REMARKS { get; set; }
    
        public virtual EMP_FIXED EMP_FIXED { get; set; }
        public virtual EMP_FIXED EMP_FIXED1 { get; set; }
        public virtual SELECTION_STATUS_MASTER SELECTION_STATUS_MASTER { get; set; }
    }
}
