//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_CLIENT
    {
        public long EMPCLINTID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> SHIP_ID { get; set; }
        public Nullable<int> RANK_CLASS_ID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual EMP_FIXED EMP_FIXED { get; set; }
        public virtual RANK_CLASS RANK_CLASS { get; set; }
        public virtual SHIP_MASTER SHIP_MASTER { get; set; }
    }
}
