//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIXED_SALARY_DETAILS
    {
        public int Id { get; set; }
        public Nullable<int> EMPSIGN_Id { get; set; }
        public string EMP_CODE { get; set; }
        public Nullable<short> EARN_DEDN_CODE { get; set; }
        public Nullable<System.DateTime> WEF_DATE { get; set; }
        public Nullable<System.DateTime> TILL_DATE { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string ADD_BY { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_TIME { get; set; }
        public string ADD_COMPUTER { get; set; }
        public string EDIT_COMPUTER { get; set; }
        public Nullable<decimal> WITHHELD_PERC { get; set; }
        public Nullable<decimal> WITHHELD_PERC_NRI { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual EMP_SIGN EMP_SIGN { get; set; }
    }
}
