//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRATUITY_CALCULATION_CREW
    {
        public int REC_NO { get; set; }
        public Nullable<byte> CLASSID { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<short> ARTICLE_DAYS { get; set; }
        public Nullable<short> STAFF_DAYS { get; set; }
        public Nullable<short> LEAVE_DAYS { get; set; }
        public string ACTIVE { get; set; }
        public string ADD_BY { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string ADD_COMPUTER { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_TIME { get; set; }
        public string EDIT_COMPUTER { get; set; }
    }
}
