//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIN_DETAILS
    {
        public int KINID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string PIN { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> EMPID { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> RELATIONSHIPID { get; set; }
    
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
        public virtual EMP_FIXED EMP_FIXED { get; set; }
        public virtual RELATIONSHIP_MASTER RELATIONSHIP_MASTER { get; set; }
    }
}
