//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIN_TABLE_DUTY_TYPE_FLAG
    {
        public int MAIN_REC_ID { get; set; }
        public string NATURE_OF_DUTY { get; set; }
        public string APPLICABLE { get; set; }
    }
}
