//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISC_TAXABLE_INCOME
    {
        public int MISC_TAXABLE_INCOME_ID { get; set; }
        public string FINANCIAL_YEAR { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public string NARRATION { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> INCOME_CODE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<decimal> UTILISED { get; set; }
        public Nullable<decimal> TAX_DED { get; set; }
        public Nullable<decimal> TAX_AMT_DED { get; set; }
        public Nullable<decimal> SCHG_DED { get; set; }
        public Nullable<decimal> CESS_DED { get; set; }
        public Nullable<decimal> HCESS_DED { get; set; }
    
        public virtual EMP_FIXED EMP_FIXED { get; set; }
        public virtual OTHER_INCOME OTHER_INCOME { get; set; }
    }
}
