//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTHER_INCOME
    {
        public OTHER_INCOME()
        {
            this.MISC_TAXABLE_INCOME = new HashSet<MISC_TAXABLE_INCOME>();
        }
    
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> NON_TAXABLE_LIMIT { get; set; }
    
        public virtual ICollection<MISC_TAXABLE_INCOME> MISC_TAXABLE_INCOME { get; set; }
    }
}
