//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTHER_EARNING_DEDUCTION
    {
        public int Id { get; set; }
        public Nullable<int> AGREEMENT_Id { get; set; }
        public string PAY_YEAR { get; set; }
        public string PAY_MONTH { get; set; }
        public string EMP_CODE { get; set; }
        public Nullable<short> EARN_DEDN_CODE { get; set; }
        public Nullable<decimal> EXC_RATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public decimal INDIAN_AMT { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> CURRENCY_Id { get; set; }
        public string ADD_BY { get; set; }
        public string ADD_COMPUTER { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string EDIT_BY { get; set; }
        public string EDIT_COMPUTER { get; set; }
        public Nullable<System.DateTime> EDIT_TIME { get; set; }
        public string ACTIVE { get; set; }
    }
}
