//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE_PERMISSION
    {
        public int PAGEPERMISSIONID { get; set; }
        public Nullable<int> PAGEID { get; set; }
        public string ROLENAME { get; set; }
        public Nullable<int> PERMISSIONID { get; set; }
    
        public virtual PAGE_MASTER PAGE_MASTER { get; set; }
    }
}
