//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYCALCULATION_LOG
    {
        public long Id { get; set; }
        public string EMP_CODE { get; set; }
        public string PAY_YEAR { get; set; }
        public string PAY_MONTH { get; set; }
        public string EMP_TYPE { get; set; }
        public string ALL_SELECTED { get; set; }
        public string CALC_COMPUTER { get; set; }
        public string CALC_BY { get; set; }
        public string CALC_DATETIME { get; set; }
    }
}
