//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_REMIT
    {
        public int PF_REMIT_ID { get; set; }
        public string REF_NO { get; set; }
        public Nullable<System.DateTime> REF_DT { get; set; }
        public string ADDR0 { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string ADDR3 { get; set; }
        public string ADDR4 { get; set; }
        public string REMIT_CHQ_NO { get; set; }
        public Nullable<System.DateTime> REMIT_CHQ_DT { get; set; }
        public string REMIT_BANK { get; set; }
        public Nullable<decimal> REMIT_AMT { get; set; }
        public string ADMN_CHQ_NO { get; set; }
        public Nullable<System.DateTime> ADMN_CHQ_DT { get; set; }
        public string ADMN_BANK { get; set; }
        public Nullable<decimal> ADMN_AMT { get; set; }
        public string AUTH_SIGN { get; set; }
        public string AUTH_DESIG { get; set; }
    }
}
