//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANK_MASTER
    {
        public RANK_MASTER()
        {
            this.RANK_CLASS = new HashSet<RANK_CLASS>();
        }
    
        public int RANKID { get; set; }
        public string RANK_DESC { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Withheld_Perc_NRI { get; set; }
        public string Print_order { get; set; }
        public Nullable<bool> Pf_Applicable { get; set; }
        public string RANK_CODE { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<RANK_CLASS> RANK_CLASS { get; set; }
    }
}
