//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATIONSHIP_MASTER
    {
        public RELATIONSHIP_MASTER()
        {
            this.KIN_DETAILS = new HashSet<KIN_DETAILS>();
        }
    
        public int RELATIONSHIPID { get; set; }
        public string RELATION { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<KIN_DETAILS> KIN_DETAILS { get; set; }
    }
}
