//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELIGION
    {
        public RELIGION()
        {
            this.EMP_FIXED = new HashSet<EMP_FIXED>();
        }
    
        public int RELIGIONID { get; set; }
        public string RELIGION_NAME { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<EMP_FIXED> EMP_FIXED { get; set; }
    }
}
