//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELECTION_STATUS_MASTER
    {
        public SELECTION_STATUS_MASTER()
        {
            this.EMP_FIXED = new HashSet<EMP_FIXED>();
            this.EMPLOYEE_STATUS = new HashSet<EMPLOYEE_STATUS>();
        }
    
        public int SPID { get; set; }
        public string SPNAME { get; set; }
        public string SPDESCRIPTION { get; set; }
    
        public virtual ICollection<EMP_FIXED> EMP_FIXED { get; set; }
        public virtual ICollection<EMPLOYEE_STATUS> EMPLOYEE_STATUS { get; set; }
    }
}
