//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_TYPE_MASTER
    {
        public SHIP_TYPE_MASTER()
        {
            this.EMP_EXPERIENCE = new HashSet<EMP_EXPERIENCE>();
            this.SHIP_MASTER = new HashSet<SHIP_MASTER>();
        }
    
        public int TypeID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<EMP_EXPERIENCE> EMP_EXPERIENCE { get; set; }
        public virtual ICollection<SHIP_MASTER> SHIP_MASTER { get; set; }
    }
}
