//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_MASTER
    {
        public SHIP_MASTER()
        {
            this.AGREEMENT_DETAILS = new HashSet<AGREEMENT_DETAILS>();
            this.EMPLOYEE_CLIENT = new HashSet<EMPLOYEE_CLIENT>();
            this.SHIP_MOVEMENT_REGISTER = new HashSet<SHIP_MOVEMENT_REGISTER>();
            this.SHIP_MOVEMENT = new HashSet<SHIP_MOVEMENT>();
            this.ShipAgreements = new HashSet<ShipAgreement>();
        }
    
        public int SMID { get; set; }
        public string VNAME { get; set; }
        public string PORT_REG_TRADE { get; set; }
        public string OFF_IMO_NO { get; set; }
        public string GT_POWER { get; set; }
        public Nullable<decimal> NO_OF_CREW { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public string ADD_BY { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public Nullable<System.DateTime> EDIT_TIME { get; set; }
        public Nullable<decimal> NRT { get; set; }
        public string AREA_OF_OPERATION { get; set; }
        public string OFFICIAL_NO { get; set; }
        public string POWER_KW_BHP { get; set; }
        public Nullable<int> COUNTRY_FLAG { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public string PHOTO { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string CALL_SIGN { get; set; }
        public string DWT { get; set; }
        public string ABS_NO { get; set; }
        public string MMSI_NO { get; set; }
        public string SAT_C_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
        public string VSAT_NO { get; set; }
        public string VCODE { get; set; }
    
        public virtual ICollection<AGREEMENT_DETAILS> AGREEMENT_DETAILS { get; set; }
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
        public virtual ICollection<EMPLOYEE_CLIENT> EMPLOYEE_CLIENT { get; set; }
        public virtual SHIP_TYPE_MASTER SHIP_TYPE_MASTER { get; set; }
        public virtual ICollection<SHIP_MOVEMENT_REGISTER> SHIP_MOVEMENT_REGISTER { get; set; }
        public virtual ICollection<SHIP_MOVEMENT> SHIP_MOVEMENT { get; set; }
        public virtual ICollection<ShipAgreement> ShipAgreements { get; set; }
    }
}
