//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATEMENT_WAGES
    {
        public long Id { get; set; }
        public string REF_PREFIX { get; set; }
        public Nullable<int> REF_NO { get; set; }
        public Nullable<System.DateTime> REF_DT { get; set; }
        public string EMP_CODE { get; set; }
        public Nullable<int> AGREEMENT_Id { get; set; }
        public Nullable<System.DateTime> SIGN_ON { get; set; }
        public Nullable<System.DateTime> SIGN_OFF { get; set; }
        public Nullable<decimal> PAYMENT_AMOUNT { get; set; }
        public Nullable<int> PREVIOUS_AGREEMENT_Id { get; set; }
        public Nullable<decimal> PREVIOUYS_DUE { get; set; }
        public Nullable<decimal> BALANCE_SALARY { get; set; }
        public string ADD_BY { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string ADD_COMPUTER { get; set; }
        public string EDIT_BY { get; set; }
        public Nullable<System.DateTime> EDIT_TIME { get; set; }
        public string EDIT_COMPUTER { get; set; }
        public string ACTIVE { get; set; }
    }
}
