//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAX_CODE
    {
        public TAX_CODE()
        {
            this.ACTUAL_SAVINGS = new HashSet<ACTUAL_SAVINGS>();
        }
    
        public int ID { get; set; }
        public string TAX_CODE1 { get; set; }
        public string DESCRIPTIONS { get; set; }
        public string SAVINGS_TYPE { get; set; }
        public string UNDER_SECTION { get; set; }
        public string INCOME_TYPE { get; set; }
        public Nullable<byte> SECTION_ID { get; set; }
    
        public virtual ICollection<ACTUAL_SAVINGS> ACTUAL_SAVINGS { get; set; }
    }
}
