//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserDetails
    {
        public int EMPID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<bool> SR_CITIZEN { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string NAME_PREFIX { get; set; }
        public string EMAIL { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public System.Guid RoleId { get; set; }
        public string RoleName { get; set; }
    }
}
