//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WITHHELD_REFUND
    {
        public int ID { get; set; }
        public int EMP_CODE { get; set; }
        public string REMARKS { get; set; }
        public string AMOUNT { get; set; }
        public string FINANCIAL_YEAR { get; set; }
        public string REF_PREFIX { get; set; }
        public Nullable<int> REF_NO { get; set; }
        public Nullable<System.DateTime> REF_DATE { get; set; }
    
        public virtual EMP_FIXED EMP_FIXED { get; set; }
    }
}
