//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WITHHELD_TRANSFER
    {
        public long WITHHELD_TRANSFER_ID { get; set; }
        public string YR { get; set; }
        public string MON { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public Nullable<decimal> TRANS_AMT { get; set; }
        public Nullable<int> AGREEMENT_CODE { get; set; }
    
        public virtual AGREEMENT_DETAILS AGREEMENT_DETAILS { get; set; }
        public virtual EMP_FIXED EMP_FIXED { get; set; }
    }
}
