//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEAR_DETAIL
    {
        public long Id { get; set; }
        public string PAY_YEAR { get; set; }
        public string PAY_MONTH { get; set; }
        public string EMP_CODE { get; set; }
        public Nullable<int> AGREEMENT_Id { get; set; }
        public string EMP_TYPE { get; set; }
        public string NATURE_OF_DUTY { get; set; }
        public string SHIP_CODE { get; set; }
        public Nullable<short> EARN_DEDN_CODE { get; set; }
        public Nullable<short> SECONDARY_EARN_DEDN_CODE { get; set; }
        public Nullable<byte> RULE_TYPE { get; set; }
        public Nullable<System.DateTime> RULE_WEF_DATE { get; set; }
        public string RATE_TYPE { get; set; }
        public string EARNING_DEDUCTION { get; set; }
        public string RANK_CODE { get; set; }
        public string CLASS { get; set; }
        public string TAXABLE { get; set; }
        public string TAX_FORECAST { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> PAY_AMOUNT { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<short> FOR_DAYS { get; set; }
        public string AMT_OR_PRCNT { get; set; }
        public Nullable<short> INDIAN_DAYS { get; set; }
        public Nullable<short> FOREIGN_DAYS { get; set; }
        public Nullable<decimal> INDIAN_AMOUNT { get; set; }
        public Nullable<decimal> FOREIGN_AMOUNT { get; set; }
        public Nullable<decimal> PROJ_TAX_PERCENT { get; set; }
        public string NRI_CALC { get; set; }
        public string SR_CITIZEN { get; set; }
        public Nullable<System.DateTime> SIGN_ON_DATE { get; set; }
        public Nullable<decimal> BASIC_FOR_PF { get; set; }
        public Nullable<decimal> LVWAGE_FOR_PF { get; set; }
        public Nullable<int> EMP_SIGN_Id { get; set; }
        public Nullable<long> MISC_Id { get; set; }
        public Nullable<long> WITHHELD_REFUND_ID { get; set; }
    }
}
